- pb_decode.c
* gcc 5.0 and 5.1 appear to take issue with this line and generates the
following error:
/home/nitro/tmp/nanopb/pb_decode.c: In function ‘pb_decode_noinit’:
/home/nitro/tmp/nanopb/pb_decode.c:889:60: error: conversion to ‘uint8_t {aka unsigned char}’ from ‘int’ may alter its value [-Werror=conversion]
fields_seen[iter.required_field_index >> 3] |= (uint8_t)(1 << (iter.required_field_index & 7));
^
* This seems like a compiler bug, but this workaround is harmless.
> decode: Fix compiler issue with gcc-5

- extra/FindNanopb.cmake
- generator/nanopb_generator.py
- generator/protoc-gen-nanopb
This pull request attempts to port `nanopb_generator.py` to a python2 *and* python3 compatible version.
Arch Linux already defaults to python3 and Ubuntu and Debian are forthcoming.  My Arch Linux install had a python-protobuf build for python3, but not for python2.  As a result, none of the hacks to force python2 worked.
I've tested this against the unit tests and it seems good for both python2 and python3.
Test systems for python3: Arch Linux up to date as of today
* clang 3.6.2-4
* cmake 3.3.2-2
* protobuf 2.6.1-1
* python 3.4.3-3
* python-protobuf 3.0.0a3-2
* scons 2.3.6-1
Python 2 testing was in a docker container running Ubuntu:14.04:
* cmake  2.8.12.2-0ubuntu3
* gcc 4:4.8.2-1ubuntu6
* protobuf 2.6.1 (built from source as 2.5.x in apt has issues with oneof it appears)
* python …
> Add proper Python3 support to the generator

- generator/nanopb_generator.py
- generator/proto/nanopb.proto
- pb.h
I have another implementation where I overload the 'anonymous' flag inside of the field rules as 'ONEOF' or 'ANONYMOUS_ONEOF'. I feel like I am relatively unfamiliar with a lot of the generator functionality so I would love feedback if you can think of a better way to do this, or at least one that is more consistent with the project style.
> Add option to allow for anonymous unions

- generator/nanopb_generator.py
This generates #defines mirroring the following values from the generated C++ code of GPB
* const Foo Foo_MIN: the smallest valid value of the enum (VALUE_A in the example).
* const Foo Foo_MAX: the largest valid value of the enum (VALUE_C in the example).
* const Foo Foo_ARRAYSIZE: always defined as Foo_MAX + 1.
The naming convention (e.g., `_MyEnum_MIN`) has been chosen to avoid conflicts with possible declared values.  `MyEnum__MIN` would be another obvious possibility.
> Generate MIN/MAX/ARRAYSIZE for enums

- AUTHORS
- docs/concepts.rst
- docs/index.rst
- docs/reference.rst
- generator/nanopb_generator.py
- generator/proto/nanopb.proto
- pb.h
- pb_decode.c
- pb_encode.c
- tests/inline/SConscript
- tests/inline/inline.expected
- tests/inline/inline.proto
- tests/inline/inline_unittests.c
This commit adds a new FT_INLINE allocation type that forces bytes
fields to be inlined into the struct. E.g., pb_byte_t my_bytes[32].
Obviously, this requires max_size for the bytes field.
> Add inline allocation of bytes fields

- pb_encode.c
Hello,
**What happens ?**
When trying to use nanopb on ARMv4 I came across a trap when encoding a message. I figured out that an unaligned access cause this. 
**How to reproduce the problem**
This occur only when you have a string of `size == sizeof(uint64_t)` and the data pointer is not aligned to a 64bit boundary.
If the type is string, do not try to deference it as int16, int32 or int64.
This may lead to unalign memory access, which may cause trap on some architectures (ARM)
> Fix potential unaligned access

- pb_decode.c
- pb_decode.h
Currently only pb_decode_varint is exposed, which has a 64-bit output and thus requires the user to deal with 64-bit integers (or truncate and handle the overflow case manually). This exposes pb_decode_varint32 (which is used all over the place internally) to users.
> Make pb_decode_varint32 public API

- docs/migration.rst
- pb_decode.c
- pb_decode.h
If pb_close_string_substream is called on a non-empty substream bytes_left will end up being decreased by more than what was actually read. This commit checks and empties out the substream first if it's non-empty.
Not a problem unless you're calling the substream functions yourself since nanopb itself always exhausts the stream before closing, but probably not the intended behaviour.
> Fix closing a non-empty substream resulting in an incorrect stream state

- CMakeLists.txt
The produced static library should be `libprotobuf-nanopb.a`
instead of the current `liblibprotobuf-nanopb.a`.
Signed-off-by: William A. Kennington III <wak@google.com>
> cmake: Fix library name

- CMakeLists.txt
When doing out of source builds:
mkdir build
cd build && cmake -G "Unix Makefiles" ../ && make
The build script tripped up on relative paths of /generator/proto and
the files under generator/proto/*.proto.
By using ${PROJECT_SOURCE_DIR}, the paths become absolute and the issue
disappears.
> CMAKE: remove use of relative paths

- extra/FindNanopb.cmake
In extra/FindNanopb.cmake, make the generated .pb.c and. pb.h files depend on the .options file (if it exists), so that editing the .options file will trigger a rebuild.
> In extra/FindNanopb.cmake, add dependency for .options files

- WORKSPACE
A WORKSPACE file is required for bazel to build the project. The
conventional naming is similar to Java packages with all special
characters including dots replaced by underscores.
> bazel: Add WORKSPACE

- pb_decode.c
- pb_decode.h
This seemed to be missing form the API.
It's simply pb_decode_delimited, but without initializing the target structure. Similar to pb_decode vs pb_decode_noinit.
This is useful for partial updates to an existing data structure, which is how I use it myself.
> Added pb_decode_delimited_noinit

- CMakeLists.txt
No need of specifying the CMAKE_PREFIX_PATH to python when asking for
sysconfig.get_python_lib since everything is installed relative to
CMAKE_PREFIX_PATH anyway.
> Fix #296 - install path of Python plugins with CMake.

- CMakeLists.txt
Allows use of a protoc binary in a non-standard location (e.g. a repository that includes a specific checked-in version of protoc).
> Add nanopb_PROTOC_PATH variable to CMakeLists.txt

- pb_decode.c
Building nanopb with clang via Xcode 8.1 fails with [-Werror, -Wswitch-enum]. This PR explicitly handles the missing enum value in the switch statement.
nanopb/pb_decode.c:334:13: error: enumeration value 'PB_WT_STRING' not explicitly handled in switch [-Werror,-Wswitch-enum]
switch (wire_type)
^
1 error generated.
> Explicitly handle all enum values in switch

- generator/proto/google/protobuf/descriptor.proto
Many options have been added to descriptor.proto since the last time it
was pulled in and nanopb will not work on .proto files using the new
options.
Addressed more permanently by https://github.com/nanopb/nanopb/pull/241
but that PR makes a series of larger changes as well.
> Updates descriptor.proto to the latest.

- generator/nanopb_generator.py
- tests/SConstruct
- tests/alltypes/alltypes.proto
- tests/alltypes/decode_alltypes.c
- tests/alltypes_proto3/SConscript
- tests/anonymous_oneof/SConscript
- tests/field_size_16/alltypes.proto
- tests/field_size_16_proto3/SConscript
- tests/field_size_32/alltypes.proto
- tests/oneof/SConscript
Fixes init values for byte types. Protoc uses octal format for default values that aren't your typical characters, which was handled incorrectly by nanopb. For example protoc turns "\xff" to "\377" which in turn is encoded character by character by nanopb (taking 4 bytes of space). This was changed in protoc at some point, nanopb 0.3.4 (iirc) worked fine.
There may still be some corner cases that aren't handled properly. Certain special characters and such. More exhaustive test cases would be good to be added.
Also did some minor changes to scons files to add python 3 support (New scons versions run on python 3 as well as 2).
Juha-Pekka Hamina
R&D engineer
Nordic Semiconductor
> Bytes init value fix

- generator/nanopb_generator.py
- generator/proto/nanopb.proto
- tests/typename_mangling/SConscript
- tests/typename_mangling/test_flatten.c
- tests/typename_mangling/test_strip_package.c
- tests/typename_mangling/with_package.options
- tests/typename_mangling/with_package.proto
In our codebase, we use protobuf `package`s and message nesting to organize code. It's great, but it means that in the resulting C code, we would have to deal with _insanely long_ identifiers such as `hw_trezor_messages_bitcoin_TxAck_TransactionType_TxInputType`. In our case, the nesting and organization is useful in other places, but not in the C codebase - it turns out that we can use a flat structure.
This patch introduces a feature that allows us to do two things:
1. strip local package name from type names - useful when you don't have cross-package references
2. strip all but the last component of the type name - useful in cases like ours, when the nested identifiers are unique and you don't need the nesting in C code.
I'm not sure if you're interested in a feature like this, or if …
> Feature: Flattening nested protobuf names

- pb_decode.c
- tests/mem_release/mem_release.c
- tests/mem_release/mem_release.proto
Hello. We've encoutered a bug and this PR contains a failing test demonstrating the issue:
If decode callbacks are used together with ([untrusted](http://jpa.kapsi.fi/nanopb/docs/security.html#division-of-trusted-and-untrusted-data)) garbage data and PB_ENABLE_MALLOC, a double-free occurs somewhere inside `pb_release`, called from `pb_decode` causing a segmentation fault.
This does not happen without PB_ENABLE_MALLOC or without decode callbacks (the test in the first commit of this PR passes)
`scons` output (tested on Debian Jessie)
```
... snip ...
[ OK ]   All patterns found in build/inline/inline.pb.h
run_test(["build/mem_release/mem_release.output"], ["build/mem_release/mem_release"])
Command line: ['build/mem_release/mem_release']
mem_release: build/common/malloc_wrappers.c:45: …
```
> pb_decode double free error with garbage input, PB_ENABLE_MALLOC and callbacks

- generator/nanopb_generator.py
Sometimes python protobuf version can't be found out by the above listed command. So added one more command to find python protobuf version which utilises pip freeze command.
> Made some changes for Error Output.

- CMakeLists.txt
Introduce options BUILD_SHARED_LIBS and BUILD_STATIC_LIBS to allow
building both types of libraries. By default only BUILD_STATIC_LIBS
is enabled.
> cmake: Allow to build a shared library

- CMakeLists.txt
If user defines non-standard directory in CMAKE_INSTALL_LIBDIR
option (i.e. /usr/lib64), then CMAKE_INSTALL_CMAKEDIR should
use it as a prefix.
> cmake: Include CMAKE_INSTALL_LIBDIR in CMAKE_INSTALL_CMAKEDIR

- extra/FindNanopb.cmake
Previously used flag (WIN32) indicated target system on which compiler
was running. Proposed change (CMAKE_HOST_WIN32) will indicate if host
system is windows.
This allows to cross compile for windows on linux machine or cross
compile for linux on windows machine. Also this change won't affect
builds for native linux or native windows.
> Correction of WIN32 flag in generator function

- extra/FindNanopb.cmake
I encountered the same as taka-no-me/android-cmake#95 problem when using buildroot.
Another more info link https://reviews.llvm.org/D41622
Can we add NO_CMAKE_FIND_ROOT_PATH to find_file and find_path?
> Append NO_CMAKE_FIND_ROOT_PATH to find_file and find_path

- generator/nanopb_generator.py
- tests/enum_minmax/SConscript
- tests/enum_minmax/enumminmax.proto
- tests/enum_minmax/enumminmax_unittests.c
Unsorted enums in message specifications do not result in correct
min/max values per the protobuf spec for cpp code:
https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#enum
The google cpp compiler uses the min/max _value_ in the message spec, so
this patch updates nanopb to do the same.
Example input:
```protobuf
syntax = "proto3";
enum Language {
UNKNOWN = 0;
ENGLISH_EN_GB = 12;
ENGLISH_EN_US = 1;
FRENCH_FR_FR = 2;
ITALIAN_IT_IT = 3;
GERMAN_DE_DE = 4;
SPANISH_ES_AR = 13;
SPANISH_ES_ES = 5;
SPANISH_ES_MX = 14;
SWEDISH_SV_SE = 6;
DUTCH_NL_NL = 7;
KOREAN_KO_KR = 8;
JAPANESE_JA_JP = 9;
CHINESE_SIMPLIFIED_ZH_CN = 10;
CHINESE_TRADITIONAL_ZH_TW = 11;
}
```
This would previously result in:
```c
#define _Language_MIN Language_UNKNOWN
#define _Language_MAX …
```
> 🔀 use min/max enum value for min/max

- extra/FindNanopb.cmake
The cmake support checks *.options files and adds plugin include option "-I" so the plugin can find it.
Currently the path is relative and cmake will assume it is relative to CMAKE_CURRENT_BINARY_DIR. Since this is source file it should be relative to CMAKE_CURRENT_SOURCE_DIR. 
I guess it will work if you build in the source dir but not in general case.
This will fix #116 if you use cmake.
> plugin include paths in cmake fix

- docs/reference.rst
- pb.h
- pb_encode.c
Don't encode scalar arrays as packed. This is only to be used when
the decoder on the receiving side cannot process packed scalar arrays.
Such example is older protobuf.js.
Fixes https://github.com/nanopb/nanopb/issues/426
> Introduce new compile time flag: PB_ENCODE_ARRAYS_UNPACKED

- CMakeLists.txt
When activating the cmake option `BUILD_SHARED_LIBS`  the created dynamic library ("protobuf-nanopbd.dll") in windows is not installed into the bin folder.
> install shared library(dll) in windows to the binary folder

- pb.h
- pb_decode.h
- pb_encode.h
This fixes clang-tidy warnings in the user's code when using nanopb encoding and decoding functions. The clang-tidy warning is related to https://wiki.sei.cmu.edu/confluence/display/c/INT13-C.+Use+bitwise+operators+only+on+unsigned+operands.
There are still many cases of this in the nanopb library, but this PR starts with just fixing the ones that end up visible in the user's code.
> Fix clang-tidy warnings about using signed integers in binary bitwise operations

- extra/FindNanopb.cmake
I have an issue when using NanoPB with Cmake in Windows. 
I want to specify an options file (Or just if the options file is in the same folder as the proto file).
The issue is that Windows is using semicolon (`:`) in path, and that interfere with the nanopb_out parsing. 
Example: Using cmake, the final command becomes :
`protoc.exe --plugin=protoc-gen-nanopb=C:/dev/build/nanopb/generator/protoc-gen-nanopb "--nanopb_out= -IC:/dev/build : C:/dev/build" C:/dev/src/data.proto`
As we can see. There is several `:` in the nanopb_out option, which lead to an error saying 
`unkonwn path /dev/build:C:/dev/build` as the parsing takes `-IC` as option and everything after is considered as the output buffer.
Solution:
NanoPB plugin options can be provided using "--nanopb_opt". 
Spliting the command …
> Split nanopb_out command on FindNanopb.cmake

- generator/nanopb_generator.py
When calling `protoc --plugin=protoc-gen-nanopb=protoc-gen-nanopb-plugin --nanopb_out=. '--nanopb_opt=--library-include-format=#include"%s"' --nanopb_opt=--no-strip-path --nanopb_opt=-xgenerator/nanopb/options.proto`, The following is given to `nanopb_generator.py` as `params`:
```--library-include-format=#include"%s"',--no-strip-path,--nanopb_opt=-xgenerator/nanopb/options.proto```
This passes the `len(args) == 1 and ',' in args[0]` check, so it then gets lexed. However, since there's a `#` character, `shlex` discards everything but: `--library-include-format=`.
Setting `lex.commenters = ''` allows `--library-include-format` to be specified in the above manner.
> Allow comma-separated option parsing to handle "#include" in options

- generator/nanopb_generator.py
- pyproject.toml
- tools/set_version.sh
This Pull request allows nanopb's generator to be built into a python package.
- Adds `poetry` as a development dependency, to build wheels from the `generator` folder.
- `pyproject.toml` project configuration file - describes the package as a whole and how to build it. (sdist)
- `nanopb_generator` script path, allows `generator/nanopb_generator` to be invoked from the CLI from any directory.
```
root@0a250617787d:~# ls
root@0a250617787d:~# nanopb_generator
Usage: nanopb_generator.py [options] file.pb ...
Options:
-h, --help            show this help message and exit
-x FILE               Exclude file from generated #include list.
```
- `protoc-gen-nanopb` script path, allows `protoc` to automatically detect the nanopb plugin. this means the plugin doesn't need to be explicitly declared! …
> Nanopb Generator as a python package

- generator/nanopb_generator.py
The temp file handling gives a Permission Denied on Windows 10, when generating the *.pb file, due to that the file is already open. This fix deals with that problem.
> Fix Windows 10 temp file handling

- generator/nanopb_generator.py
- tests/special_characters/funny-proto+name has.characters.proto
Hello,
while using nanopb I noticed a bug in the python generator. I think my extended special character test case should make clear what the problem is. However, I try to put it in words below. 
Naming message (struct) members in a .proto file `X` or `a` crashes with the automatic `message_FIELDLIST` macro generation of the nanopb python generator.  The macro uses `X` and `a` as parameters. If the generated *.pb.[ch] files are now compiled, the preprocessor will replace also the member name in the macro which is IMO not intended.
In most cases a .proto snippet
```
message SimpleMessage {
required int32 fieldname = 1;
}
```
is converted to a macro like this
```
#define X_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    fieldname,                 1)
```
However, using the following …
> Fix fieldlist macro geneartion for special struct members X and a

- generator/nanopb_generator.py
- generator/proto/nanopb.proto
- tests/options/options.proto
- tests/options/options_h.expected
I propose to add an option, which would allow to override type of variable in generated C structs.
It is useful, if you have many different types of (enum) fields, but want them to be of the same type in C. This allows to use a single method to update field values, or store pointers to these fields in an array.
Of course, using this option requires extra carefulness, because mismatching an override type will result in all sorts of issues. Although, anyone, who has a need for such options, will likely be aware of the possible consequences
> Added type_override option, and its handling to generator

- pb_encode.c
- tests/regression/issue_504/SConscript
- tests/regression/issue_504/test.c
- tests/regression/issue_504/test.proto
**Steps to reproduce the issue**
See the attached test case
**What happens?**
On `pb_encode`, `pb_check_proto3_default_value` may improperly consider submessages as being empty (set to  default value) when FT_POINTER fields are used.
It is only checking the `field->data_size` first byte(s) of the pointer, which for strings or bytes is 1, so if an pointer happens to be aligned on 0x100 it'll be considered as being NULL.
**What should happen?**
Non empty submessages should always be serialized.
**Notes**
Fixing PB_SINGULAR_POINTER `field->data_size` to actually be a full pointer size seems to work without breaking other tests cases `pb_membersize(st, m[0])` -> `pb_membersize(st, m)`. But this leads to OOBW on `pb_decode`.
This bug is not present in 0.4 and onward thanks to `has_submessage`.
> Regression test + fix for proto3 submessage improperly considered empty

- extra/FindNanopb.cmake
* As cmake find file is named 'FindNanopb.cmake' users are required
to use `find_package(Nanopb)` to find nanopb. cmake >= 3.17 warns
if package name (NANOPB up to now) and name used within find_package
to not match. This changes to name to Nanopb. As the found variable
is always with with UPPERCASE as well, this should be backwards
compatible for users.
* Fixes Issue #506
> Use Nanopb as cmake package name.

- extra/FindNanopb.cmake
* find_package(PythonInterp) is deprecated and the set variables
are anyhow not used anywhere
> Remove find_package(PythonInterp)

- extra/FindNanopb.cmake
The custom command currently claims to output a file with the relative path included, but actually creates a file without the relative path.
This change creates files in the relative path directory.
> Fix nanopb_out path in cmake command

- extra/FindNanopb.cmake
- generator/nanopb_generator.py
to allow other systems without the ':' in their path to use older versions of protoc
> use split --nanopb_opt only on Windows

- CMakeLists.txt
This removes the Python 2.7 interpreter requirement for `cmake` and fixes issues when build systems may be using nanopb but no longer support Python 2.
**Steps to reproduce the issue**
* Run `cmake .` on a system without Python 2.7, or
* Integrate into a build system that installs required packages for Python3
**What happens?**
* cmake fails to find an appropriate python version, or
* Building fails since required packages may not be installed for Python 2.7
**What should happen?**
* cmake should use the default Python interpreter
> Relax cmake python interpreter requirements to support Python3.

- generator/nanopb_generator.py
- tests/regression/issue_535/SConscript
- tests/regression/issue_535/issue_535.proto
Protobuf:
```proto
syntax = "proto3";
enum Foo {
option allow_alias = true;
Bar = 0;
Baz = 1;
Bag = 1;
}
```
Gives this exception:
```
$ nanopb_generator -D src test.proto 
Traceback (most recent call last):
File "/usr/local/bin/nanopb_generator", line 8, in <module>
sys.exit(main_cli())
File "/home/tassadar/.local/lib/python3.8/site-packages/nanopb/generator/nanopb_generator.py", line 1929, in main_cli
results = process_file(fdesc.name, fdesc, options, other_files)
File "/home/tassadar/.local/lib/python3.8/site-packages/nanopb/generator/nanopb_generator.py", line 1866, in process_file
headerdata = ''.join(f.generate_header(includes, headerbasename, options))
File "/home/tassadar/.local/lib/python3.8/site-packages/nanopb/generator/nanopb_generator.py", line 1500, in generate_header
yield …
```
> Fix nanopb_generator exception on enums with aliases

- generator/nanopb_generator.py
- tests/infinity_nan/SConscript
- tests/infinity_nan/floats.proto
- tests/infinity_nan/infinity_nan_test.c
Fix for https://github.com/nanopb/nanopb/issues/530.
The proto2 spec allows floating-point fields to have default values of 'inf', '-inf', 'nan' or '-nan'. The generator script copies these directly into source code, where they fail to compile (they do parse correctly in Python).
This change adds the following conversions for generated C code:
inf -> INFINITY
nan -> NAN
and adds an include for <math.h> where one of these occurs.
Note: The macros INFINITY and NAN are C99 features, so this won't work for strict ANSI C. However, the user can supply their own macro definitions in that case.
> Add support for infinity and nan floating-point defaults (#530)

- generator/nanopb_generator.py
- tests/alltypes/alltypes.proto
- tests/alltypes/decode_alltypes.c
- tests/alltypes/encode_alltypes.c
- tests/alltypes_callback/decode_alltypes_callback.c
- tests/alltypes_callback/encode_alltypes_callback.c
- tests/alltypes_pointer/decode_alltypes_pointer.c
- tests/alltypes_pointer/encode_alltypes_pointer.c
- tests/common_unittests/common_unittests.c
- tests/field_size_16/alltypes.proto
- tests/field_size_32/alltypes.proto
- tests/package_name/SConscript
- tests/package_name_nanopb/SConscript
Fix for https://github.com/nanopb/nanopb/issues/532.
According to https://developers.google.com/protocol-buffers/docs/proto#optional, when a proto2 enum field does not specify a default value, the default value is the first declared enum value, which may not be zero. For an enum with non-zero first value and a field with no default, the decoder was setting the field to zero, instead of the first enum value.
> Set proto2 enum fields to first value when no default is given, even if nonzero (#532)

- CMakeLists.txt
This issue was addressed in bug #296, and recently broken again.
> Fix so python files are installed relative to CMAKE_INSTALL_PREFIX.

- CMakeLists.txt
This patch installs the missing _utils.py and nanopb_pb2.py into the
expected proto/ subfolder.  Otherwise the generator script imports will
not find them in the proper namespace.
It also installs the generator and wrapper scripts in
CMAKE_PREFIX_PATH/bin/. WIN32 is handled specially since it has a
separate wrapper (.bat).
> Install missing _utils.py and binary/wrappers.

- generator/nanopb_generator.py
- tests/cxx_callback_datatype/SConscript
- tests/cxx_callback_datatype/cxx_callback_datatype.cc
- tests/cxx_callback_datatype/cxx_callback_datatype.cpp
- tests/cxx_callback_datatype/message.proto
- tests/site_scons/site_tools/nanopb.py
Option '(nanopb).callback_datatype' does not work with
most C++ types, because generated structure is inside
an 'extern "C" {' block, that prevents using namespaces, templates...
Option '(nanopb_fileopt).include' does not support including system headers,
that prevents using `<vector>`, `<string>`, etc...
Modify generator in following ways:
- start 'extern "C" {' later, after the structures
- for include option stating with `'<'`, include system header
e.g. `"(nanopb_fileopt).include = '<vector>'"` generates `"#include <vector>"`
Add 'cxx_callback_datatype', SConscript code based on 'cxx_descriptor' test.
> Better support C++ types in generated structs

- Package.swift
The platform specifications cause a build warning in Xcode 12. They're not necessary since nanopb supports all versions supported by Xcode versions that support Swift Package Manager.
Details in https://github.com/firebase/firebase-ios-sdk/issues/6449, https://forums.swift.org/t/minimum-ios-version-xcode-12-and-build-warnings/40224, and https://github.com/apple/swift-evolution/blob/master/proposals/0236-package-manager-platform-deployment-settings.md
> SPM: Fix iOS Build warning

- extra/FindNanopb.cmake
When calling NANOPB_GENERATE_CPP() multiple times with cmake ninja generator, one will run into following issue:
```
ninja: error: build.ninja:14698: multiple rules generate nanopb/generator/proto/nanopb_pb2.py [-w dupbuild=err
```
> Allow multiple targets to be created by calling NANOPB_GENERATE_CPP()

- conanfile.py
Without this, there will be no links against the nanopb library when
nanopb is integrated by conan
Fixes #604
> Add protobuf-nanopb library to cpp_info.libs

- generator/nanopb_generator.py
As requested in #603 ,
New option "--version" was added to nanopb_generator.py that will print nanopb's version and exit.
This option is supported in both CLI and protoc-plugin mode.
> Add '--version' option to nanopb_generator.py

- pb_encode.h
There is a small typo in pb_encode.h, spm_headers/nanopb/pb_encode.h.
Should read `specifying` rather than `specifing`.
> docs: fix simple typo, specifing -> specifying

- pb_decode.c
The 0.4 branch contains commit 2519119babea ("Verify stream size before allocating string / bytes."):
This stops ridicuously large mallocs from getting through
on length-limited streams or buffers. Typically you should
also override realloc() to limit allocation size yourself
if dealing with untrusted data in pointer mode, but this
at least limits the potential denial-of-service attacks.
Backport this patch in 0.3 maintenance branch in order to make fuzzing not crash as soon as the decoder tries to allocate a large buffer.
More precisely, while fuzzing a project using Nanopb 0.3.9.7 with libFuzzer, I got the following log:
```text
==16129== ERROR: libFuzzer: out-of-memory (malloc(3200220908))
To change the out-of-memory limit use -rss_limit_mb=<N>
#0 0x528101 in …
```
> Backport "Verify stream size before allocating string / bytes."

- .gitignore
- BUILD.bazel
- WORKSPACE
This formats both the BUILD.bazel and WORKSPACE files with the official Bazel formatter, called buildifier. Formatting separately will reduce noise in subsequent changes.
> Buildify BUILD and WORKSPACE files

- CMakeLists.txt
The variable PYTHON_INSTDIR is not initialized if the option
nanopb_BUILD_GENERATOR is OFF
> Fixing uninitialized PYTHON_INSTDIR in CMakeLists.txt

- CMakeLists.txt
If you add nanopb as a submodule. The headers won't be available correctly when building other projects in the superbuild.
Therefore I've added the `$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>`
> [CMake] add build interface

- CMakeLists.txt
this PR is a followup of #669
* Canges the raw `nanopb_PROTOC_PATH` with a find_program approch which is more the "cmake way to do".
* Adds the missing build interface for the shared build
* Adds component Interpreter to find python since only the interpreter is needed
* Removes some whitespaces to get a unified form.
> Unify CMake

- CMakeLists.txt
-The old way was wrong and would report errors when protoc was found. The correct way to do it manually would be to use if(NOT EXISTS ${nanopb_PROTOC_PATH})
> Use CMAKE inbuilt mechanic to decide if protoc was found

- pb.h
IAR compiler provides a `static_assert` keyword that can be used to prevent a compiler error due to `_Static_assert` not being available.
Related: #589
> Use 'static_assert'  keyword for iar

- docs/reference.md
The option is called `PB_CONVERT_DOUBLE_FLOAT`:
https://github.com/nanopb/nanopb/blob/11885ad8b80cc1ecddc57a03da6dbc9e53cdf1e8/pb.h#L175-L180
> Fix PB_CONVERT_DOUBLE_FLOAT option in docs

- CMakeLists.txt
- generator/nanopb_generator.py
As of Python 3.10, the `distutils` module is deprecated ([PEP 632](https://www.python.org/dev/peps/pep-0632/)), and importing it triggers a warning.
This PR removes all references to `distutils` from nanopb.
> Remove dependency on Python distutils

- CMakeLists.txt
I realized my previous PR introduced a small regression in the install directory. `Python_SITELIB` is an absolute path (e.g. `/usr/lib/python3.10/site-packages` on my machine), whereas the previous distutils method would produce a relative path (`lib/python3.10/site-packages`). Using `os.path`, this behaviour can be replicated in a platform-independent manner.
Tested old vs. new on Linux and Windows.
> fix python site-packages install path

- pb_decode.c
- pb_encode.c
**Description:**
Enabling `PB_BUFFER_ONLY` should speed up execution ([ref](https://github.com/nanopb/nanopb/blob/1d43d109af32ef2b083ba0312259e2e06407f023/docs/reference.md))
When the flag is set, the `buf_read`/`buf_write` functions are used to copy data from/to a stream respectively.
Using iteration is much inferior to `memcpy`.
In my case, switching to `memcpy` increased the performance by a factor of 8.
> Use memcpy instead of iterating on buf_read/write

- BUILD.bazel
I needed to add these before I was able to import `nanopb.proto`.
Tested here with the following code sections:
https://github.com/BetzDrive/bldc-controller/blob/f5d91c1aa8525789434d0f0c76391e85edfd2169/firmware/proto/BUILD.bazel#L3-L8
https://github.com/BetzDrive/bldc-controller/blob/f5d91c1aa8525789434d0f0c76391e85edfd2169/firmware/proto/messages.proto#L1-L4
@silvergasp not sure if you had a different way of doing this. Since you started bazelifying this, I'd appreciate your input!
> [Bazel] Allows importing nanopb.proto when defining proto libs

- generator/nanopb_generator.py
This causes MSGTYPE macros to generate for UENUM fields so that the enum types can be inferred by macro expansions. 
Without this there seems to be no way to deduce the type name of an enum in a protobuf message field from the preprocessor.
This allows for macro constructions that automatically call the ENUMTYPE_name() functions generated by the enum_to_string feature.
> Generate MSGTYPE definitions for UENUM fields

- pb.h
I have production code in C and I'm using C++ test framework and that caused some linkage problems with nanopb. This patch fixed my problem and hopefully some others too.
> Allow including inside of extern C

- library.json
This should allow LDF to find dependency in default (chain) mode without specifying it explicitly.
ref #818
> PlatformIO: Added `includeDir` to `build` section of the library.json.

- generator/nanopb_generator.py
The `enum_to_string` function is declared outside of the `extern "C"` block, making it unusable in C++ code.
> Move extern block to accommodate enum functions

- generator/platformio_generator.py
- This PR mainly fixes #834 by placing path arguments to the Nanopb generator in the CMD array separately to avoid possible issues if paths contain spaces
- Other minor improvements
> Improve PlatformIO generator to handle spaces in paths

- pb.h
MSVC defaults to C89 mode where `_Static_assert` doesn't work, but this does.
> Use static_assert keyword on MSVC in C89 mode (#843)

- generator/nanopb_generator.py
Avoid garbled code generated when annotating proto in Chinese or other languages.
> ref |> Modified The generated code uses utf-8 encoding by default.

- CMakeLists.txt
Hello nanopb team,
I've been struggling to get local builds of nanopb integrated on various build systems. The pain point has been the nanopb `proto` python module installation location. To make this easier for myself and other nanopb users, I'd like to propose this change:
Add a `PATH` option to the cmake build named `nanopb_PYTHON_INSTDIR_OVERRIDE`. When set, cmake will use this path as the python install path and skip the `find_package(Python ...)` and `execute_process(COMMAND ${Python_EXECUTABLE} ...)` steps.
> Add nanopb_PYTHON_INSTDIR_OVERRIDE to CMakeLists.txt

- docs/migration.md
- docs/reference.md
- generator/nanopb_generator.py
- tests/enum_sizes/SConscript
- tests/enum_sizes/enumsizes.proto
- tests/enum_sizes/enumsizes_intsize_unittests.cc
- tests/enum_sizes/enumsizes_intsize_unittests.h
- tests/enum_sizes/enumsizes_unittests.c
While the [`packed_enum`](https://github.com/nanopb/nanopb/blob/91fb301dabb83beb28f2ad266be6aaee7a1a4e00/generator/proto/nanopb.proto#L76) option exists, this does not work when using the MSVC compiler. 
This PR adds the ability to specify the size of the generated enums (this works for C++ only)
> Add ability to specify size of generated enums

- generator/platformio_generator.py
Right now, proto files can only be built in platformio from proto files in the parent repo (since they have stable path). If the proto files are in a library, the checkout path will be environment dependent, requiring an environment name substitution in the path.
Allows building protos found in libraries by using ${PIOENV} substitutions like so:
`custom_nanopb_protos = +<.pio/libdeps/${PIOENV}/some_library/proto/*.proto>`
I haven't extensively tested this change, but I can confirm that it works to solve the problem I ran into.
The expected change is simply that [interpolation of values](https://docs.platformio.org/en/latest/projectconf/interpolation.html) will now work on the custom_nanopb_protos platformio argument.
> Allow variable interpolation in custom_nanopb_protos for platformio builder

- extra/FindNanopb.cmake
Fix relative path passed to protoc when using RELPATH but NANOPB_GENERATE_CPP_APPEND_PATH not set. In this case the path provided by RELPATH should be passed to protoc first instead of the current source directory.
This was working before and broke with 8cc860c.
> Fix first path passed to protoc

- README.md
- generator/nanopb_generator.py
- tests/proto3_optional/SConscript
- tests/typename_mangling/SConscript
- tests/typename_mangling/test_strip_package_dependencies.c
- tests/typename_mangling/with_package_a.proto
- tests/typename_mangling/with_package_b.proto
Fixes #865
When proto file _B_ defines `MessageB` containing a field with type `MessageA` that is defined in proto file _A_ which is using name mangling, stripping package names in this case, the `_init_zero` and `_init_default` `#defines` in file _B_ still use the long names from file _A_ and fail to compile. Similarly, the `_MIN`, `_MAX`, and `_ARRAYSIZE` `#defines` only use shorter identifiers.
This solution tries to follow the existing behavior of creating a `#define` mapping from long names to short names when using name mangling. It checks if the identifier is mangled, and populates the `MangleNames.reverse_name_mapping` dictionary with both the identifiers, ensuring both conform to the naming style. I included a test for this behavior.
This also includes two other bug fixes, but …
> Support stripping package names with a dependent proto file

- BUILD.bazel
This should fix https://github.com/nanopb/nanopb/issues/890 by adding all the required source and data files needed for the `protoc` generator.
> Add missing source and data files to `protoc-gen-nanopb`

- generator/nanopb_generator.py
- tests/message_sizes/dummy.c
This PR modifies the nanobp_generator.py script to generate a `#define` of the largest message size. This facilitates setting the size of static arrays to be the largest possible encoded message size
> Provide the maximum message size

- BUILD.bazel
- extra/bazel/nanopb_deps.bzl
- extra/bazel/rules_proto_grpc.patch
- tests/bazel_options_support/bazel_options_support.cc
Making a PR out of the suggestion in https://github.com/nanopb/nanopb/issues/805#issuecomment-1338272685 to support `.options` files in the provided bazel rules.
I added a bazel test to test the new support (failing on first commit, passing on second commit).
> Add support for .options files in bazel rules

- .github/workflows/cmake.yml
- CMakeLists.txt
- docs/migration.md
- extra/script_wrappers/nanopb_generator.py
- extra/script_wrappers/nanopb_generator.py.in
- generator/nanopb_generator
- generator/nanopb_generator.bat
Previously CMakeLists.txt would install the nanopb components as a Python package called `proto`.
This would conflict with other packages (such as `python3-proto-plus`) (#845).
This pull request changes the directory structure to match what `pip install nanopb` produces.
The Python package is now called `nanopb`, and there are small wrapper scripts installed under `bin` to import the module.
Also added a GitHub workflow to test CMake installation.
@nicholas-stpierre-simplisafe @avikde @ianjfrosst @shahsahi If any of you has time to try out CMake installation from the branch dev_cmake_python_install that would be great. Just in case there is some regression for existing users.
> Change CMake Python package name to nanopb

- tests/SConstruct
Trying to compile and run tests using IAR compiler i came across the following issue:
`CheckCCFlags('','-lm') ` always succeeeds even when libm doesn't exist since it doesn't actually try to link.
The Code in question:
https://github.com/nanopb/nanopb/blob/5fd8f04a48be1a250c3bbdc9f7c782ef2c372e74/tests/SConstruct#L84
Excerpt from config.log
```
scons: Configure: Checking support for CCFLAGS="" LINKFLAGS="-lm"...
scons: Configure: "build/config/conftest_cf2934b4600b480723adfae3b58d5f1b_0.c" is up to date.
scons: Configure: The original builder output was:
|build/config/conftest_cf2934b4600b480723adfae3b58d5f1b_0.c <-
|  |int main() {return 0;}
|
scons: Configure: "build/config/conftest_cf2934b4600b480723adfae3b58d5f1b_0_f31a9d447b06d437e00c7f1832a0495d.o" is up to date.
scons: Configure: …
```
> Change check_ccflags to TryLink

- generator/nanopb_generator.py
- tests/cxx_descriptor/message.proto
- tests/cxx_descriptor/message_descriptor.cc
The existing C++ message descriptors are useful for use in templated message packing/unpacking code.
This PR adds has_msgid() and msgid() methods for the MessageDescriptor<> class.
> Add has_msgid() and msgid() methods to C++ message descriptors

- generator/nanopb_generator.py
- tests/cxx_descriptor/SConscript
- tests/cxx_descriptor/message.proto
- tests/cxx_descriptor/message_descriptor.cc
This adds a max_size field referring to the C #define, indicating the maximum encoded size of that message type. If the size cannot be determined, for example due to non-bounded repeated fields, the constant is omitted.
If anyone knows how to test for absence of types in C++ I'm all ears :)
This closes #932
> Add message sizes to C++ wrappers.

- Package.swift
- spm_resources/PrivacyInfo.xcprivacy
Add a privacy manifest for nanopb. The library does not use any ["required reason API"](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc).
Proposing to:
- merge this in the `maintenance_0.3` branch
- publish a `0.3.9.10`  tag after merging
Fixes #910
cc: @paulb777
> [nanopb] Add Apple privacy manifest

- README.md
- zephyr/module.yml
This PR allows using `nanopb` as a [zephyr](https://docs.zephyrproject.org/latest/services/serialization/nanopb.html) module directly, instead of maintaining/merging a specific downstream copy.
> Support zephyr module

- CMakeLists.txt
- extra/FindNanopb.cmake
- generator/proto/__init__.py
When building with CMake we should prefer to use the `protoc` executable that uses grpcio-tools.
Fixes #953
> Prefer `generator/protoc` in CMake

- generator/nanopb_generator.py
- generator/proto/nanopb.proto
- tests/options/proto3_options.expected
- tests/options/proto3_options.proto
This lets proto3 files define submessage fields which nanopb treats as required (even though proto3 doesn't support 'required'). This means that nanopb won't generate a has_xxx field, will reject messages where this field is missing, and will always serialize the field. However, other consumers of the proto file won't see the field as required, and are therefore safe to it being removed in future.
To do this, use:
Submessage some_submessage = 1 [(nanopb).label_override = LABEL_REQUIRED];
This mechanism also lets users change whether nanopb treats the field as optional or repeated in both proto2 and proto3.
Fixes: #962
> Add label_override field option

- pb_decode.c
- pb_encode.c
The GCC attribute `warn_unused_result` is supported by the IAR compiler starting from version 9.40.1.
> Add supported GCC attributes for IAR compiler

- extra/FindNanopb.cmake
Similar to searching for the local `protoc`, we should use the local `nanopb_generator.py` script.
The issue was reported at https://github.com/zephyrproject-rtos/zephyr/issues/70065#issuecomment-2133261857
> Do not include system paths when finding generator script

- extra/FindNanopb.cmake
Fix nanopb failure to take into account the `*.options` files when using CMake if the path to the source tree contains spaces.
The bug is due to an extra space between `--nanopb_opt=` and the first `-I` in `NANOPB_PLUGIN_OPTIONS` (no idea why it matters here).
1. Clone and build the test example:
```sh
git clone https://github.com/gsurkov/nanopb-test.git --recursive "path with spaces"
cd path\ with\ spaces
mkdir && cd build
cmake .. && cmake --build .
```
2. Check the output files:
```sh
cat test.pb.h
```
The test struct will be defined as
```c
/* Struct definitions */
typedef struct _Test_Test {
pb_callback_t test;
} Test_Test;
```
which is incorrect, as the `test` field is defined as `FT_POINTER` in the options file.
3. Checkout the branch containing the fix and rebuild everything: …
> Fix source tree paths with spaces

- extra/FindNanopb.cmake
Surround the `NANOPB_PLUGIN_OPTIONS` with quotation marks to make it expand properly into an empty string.
Same as #971
> Surround NANOPB_PLUGIN_OPTIONS with quotation marks

- CMakeLists.txt
- tools/set_version.sh
(Related to CMake warning: "policy CMP0048 is not set: project() command manages VERSION variables")
> Set project() version correctly to avoid CMake warning

- .github/workflows/binary_packages.yml
This *should* fix #972 , although I am not completely sure.
As I mentioned in https://github.com/nanopb/nanopb/issues/972#issuecomment-2236295006 this seems to be a really weird issue. My guess is that this is due to GitHub not correctly sanitizing the systems between jobs.
The problems I mentioned in #989 caused me problems with testing, but by running some jobs in a different branch, it seems that adding the `actions/setup-python@v5` action should do the trick.
I have had three jobs in a row succeed:
- https://github.com/jaskij/nanopb/actions/runs/9991129469/job/27613287656
- https://github.com/jaskij/nanopb/actions/runs/9991087641/job/27613159772
- https://github.com/jaskij/nanopb/actions/runs/9991020187/job/27612941035
> ci: binary_packages: add actions/setup-python

- .github/workflows/binary_packages.yml
- .github/workflows/trigger_on_code_change.yml
- generator/proto/__init__.py
- generator/proto/_utils.py
Due to #887 , it occurred to me it may be a good idea to test on the latest version of Python as well, among others to get early warnings of deprecations.
> run binary_packages on Python 3.8, and on latest 3.x

- MODULE.bazel
- generator/proto/google/protobuf/descriptor.proto
The descriptor.proto lives in this repo https://github.com/nanopb/nanopb/blob/master/generator/proto/google/protobuf/descriptor.proto is 6-year old, I wonder if it is possible to update it so that we can upgrade protobuf version for bazel.
> update descriptor.proto to latest

- generator/nanopb_generator.py
Protobuf's MakeClass() function has been deprecated. According to [the source code](https://github.com/protocolbuffers/protobuf/blob/95ef4134d3f65237b7adfb66e5e7aa10fcfa1fa3/python/google/protobuf/reflection.py#L66C1-L66C4) it will be removed in Jan 2025.
Building C files with nanopb calls the deprecated function, and throws a warning on my machine when using the pip protobuf package v5.28.1.
This PR replaces the function call with the one recommended in the the source code.
> Replace deprecated call to protobuf.reflection.MakeClass()

- pb.h
- pb_encode.c
As part of my work integrating nanopb into ZMK (by way of the Zephyr integration), like many others I've been hit with some high stack usage. The attached changes helped drop the usage by about 300bytes with my testing. The current ZMK PR integrating this change is up at https://github.com/zmkfirmware/zmk/pull/2505
* Add option for skipping size checks when encoding submessages
* Tweak inline/noinline for functions to reduce stack size.
Not sure if this is something you'd be interested in, but I wanted to at least propose upstream here. Thanks for the project!
> Various stack size reduction tweaks

- generator/nanopb_generator.py
- tests/namingstyle/naming_style.proto
- tests/namingstyle/test_naming_style_c.c
Fixes #1014 
The first commit adds a test that fails because it generates an undeclared identifier `MyEnum1_ENTRY_Second` in `MAIN_MESSAGE_INIT_DEFAULT` instead of the expected `MY_ENUM1_ENTRY_SECOND`. The second commit fixes it by utilizing the configured naming style for enum values. 
Given the following _test.proto_ file:
```protobuf
syntax = "proto2";
enum MyEnum {
ValueOne = 1;
ValueTwo = 2;
}
message Msg {
required MyEnum enum = 1 [default = ValueOne];
}
```
Running `python3 nanopb_generator.py --c-style` would previously result in the following _test.pb.h_ (only relevant definitions included):
```c
/* Enum definitions */
typedef enum my_enum {
MY_ENUM_VALUE_ONE = 1,
MY_ENUM_VALUE_TWO = 2
} my_enum_t;
/* Initializer values for message structs */
#define MSG_INIT_DEFAULT …
```
> Fix inner enum naming with a default value

- pb_decode.c
```
nanopb/pb_decode.c:309:5: warning: enumeration value 'PB_WT_PACKED' not handled in switch [-Wswitch-enum]
309 |     switch (wire_type)
|     ^~~~~~
nanopb/pb_decode.c: In function 'read_raw_value':
nanopb/pb_decode.c:325:5: warning: enumeration value 'PB_WT_PACKED' not handled in switch [-Wswitch-enum]
325 |     switch (wire_type)
|     ^~~~~~
```
To get rid of this warning, adds cases in `pb_decode.c` for the `PB_WT_PACKED` wire type. In `pb.h`, it's states it is an internal marker for arrays and I assume an invalid wire type. Treating it as such in the switch/case
> Add cases for `PB_WT_PACKED`

- docs/reference.md
- generator/nanopb_generator.py
- tests/namingstyle_custom/SConscript
- tests/namingstyle_custom/custom_naming_style.options
- tests/namingstyle_custom/custom_naming_style.proto
- tests/namingstyle_custom/custom_naming_style.py
- tests/namingstyle_custom/custom_naming_style_mangle.options
- tests/namingstyle_custom/custom_naming_style_mangle.proto
- tests/namingstyle_custom/custom_naming_style_package.options
- tests/namingstyle_custom/custom_naming_style_package.proto
- tests/namingstyle_custom/test_custom_naming_style_c.c
- tests/namingstyle_custom/test_custom_naming_style_mangle_c.c
- tests/namingstyle_custom/test_custom_naming_style_package_c.c
This is an attempt to support custom naming by loading a python module via a module path and class name. I'm happy to hear feedback and suggestions for alternate approaches. I added a test named _namingstyle_custom_, which was copied and modified from _namingstyle_ to use fewer delimiters and more camel and pascal casing.
I tried to make this more flexible by also passing a class name but it could be simplified by requiring a specific class name if that's preferred. I first tried to pass the arguments in as a tuple (`nargs=2` in `optparser.add_option`) but that didn't seem to play nice when trying to run the tests or running it as a plugin; it kept getting split. I could wrap it in single quotes but then I'd have to strip those which felt wrong, so I switched to passing a single delimited …
> Support custom naming styles

- .gitignore
- generator/nanopb_generator.py
- tests/namingstyle_custom/SConscript
- tests/namingstyle_custom/custom_naming_style_importer.options
- tests/namingstyle_custom/custom_naming_style_importer.proto
- tests/namingstyle_custom/custom_naming_style_other.options
- tests/namingstyle_custom/custom_naming_style_other.proto
- tests/namingstyle_custom/test_custom_naming_style_importer_c.c
This fixes #1027 which has an example of the problem. I added a test that breaks and demonstrates the issue, and then fixed it in the following commit.
Here is a snippet from the imported _custom_naming_style_other.pb.h_:
```c
/* Enum definitions */
typedef enum _TheOtherEnum {
THE_OTHER_ENUM_OTHER_UNSET = 0,
THE_OTHER_ENUM_OTHER_SET = 1
} TheOtherEnum;
typedef enum _AnotherEnum {
ANOTHER_ENUM_ANOTHER_UNSET = 0
} AnotherEnum;
/* Mapping from canonical names (mangle_names or overridden package name) */
#define other_THE_OTHER_ENUM THE_OTHER_ENUM
#define THE_OTHER_ENUM OtherTheOtherEnum
#define OtherTheOtherEnum TheOtherEnum
#define other_AnotherEnum AnotherEnum
#define OtherAnotherEnum other_AnotherEnum
```
It now also provides a definition for the styled/unmangled type names. The tricky …
> Fix custom naming styles

- BUILD.bazel
The `py_proto_library` has been deprecated from the `protobuf` repo. Instead, it recommends using the `py_proto_library` from `rules_python`.
https://github.com/protocolbuffers/protobuf/commit/1e8e356b888eb5e7125c7fe0743f402447db14bc
Additionally, if you want to use proto toolchains (see here: https://github.com/aspect-build/toolchains_protoc) then the `protobuf` implementation will not work as it depends directly on `@com_google_protobuf//:protoc` instead of relying upon toolchain resolution. `rules_python`'s fixes this.
> [bazel] Use rules_python py_proto_library

- zephyr/module.yml
Update the `zephyr/module.yml` with pip requirements.
Zephyr has introduced an extension which allows external modules to describe Python dependencies for `pip`.
See https://github.com/zephyrproject-rtos/zephyr/pull/80782
> Add pip requirements file for zephyr module

- BUILD.bazel
As I dug more into the issue discussed in
https://github.com/nanopb/nanopb/pull/1034 (a collision between the protoc versions in `MODULE.bazel` and `grpcio-tools`), I realized that it surfaced only because of the dependency on `grpcio-tools` in the plugin binary.  But this dependency is unnecessary. The purpose of the `grpcio-tools` dependency in general is to allow nanopb to invoke protoc. But we don't need to do this from this target:
1. We never need to rebuild nanopb_pb2.py ourselves, because we have a dep on `:nanopb_py_proto`. (So, we can set `NANOPB_PB2_NO_REBUILD=1`.)
2. The protoc-gen-nanopb binary is meant to be invoked as a protoc plugin, so it doesn't need to invoke protoc itself at runtime.
This PR fixes the same issue, and in a more durable way. If version skew between the …
> bazel: Tidy up protoc-gen-nanopb

- generator/platformio_generator.py
Allow to set custom project directory for the PlatformIO script.
Normally, the script expects the proto files in the PlatformIO project directory. However, in my case I pull the files as an external dependency. The optional flag `custom_nanopb_project_dir` allows to override the default behavior.
Example usage:
```
custom_nanopb_project_dir = ${PROJECT_LIBDEPS_DIR}/${PIOENV}/my-project-protobuf
custom_nanopb_protos =
+<proto/types.proto>
+<proto/device.proto>
+<proto/states.proto>
+<proto/settings.proto>
+<proto/analytics.proto>
```
> [PlatformIO] Add custom project dir option

- tools/set_version.sh
- zephyr/module.yml
Adds version generation of PURL and CPE for Zephyr (https://github.com/nanopb/nanopb/issues/1041).
Question would be what PURL to use: `pkg:generic/nanopb`  is already used by e.g. OSV  (https://test.osv.dev/vulnerability/OSV-2020-1567) or `pkg:github/nanopb/nanopb` which would be closer to the purl spec https://github.com/package-url/purl-spec?tab=readme-ov-file#some-purl-examples  
Are there any other scanners already nanopb PURLs?
> add version generation for CPE and PURL in zephyr/module.yml

- generator/nanopb_generator.py
`inline`s alone for the static functions of `MessageDescriptor`s are sometimes not enough for some use cases. These changes make them more useful.
> PB_INLINE_CONSTEXPR for fields() has_msg_id() and msg_id()

- BUILD.bazel
When building nanopb with Bazel, the developer may want to define their own compilation options (https://jpa.kapsi.fi/nanopb/docs/reference.html#compilation-options). Today, that is do able with a global `-Ddefine` specified via the command line. But that doesn't support use cases such as `PB_SYSTEM_HEADER` where additional header files need to be support.
It also forces the `defines` for nanopb to be applied to all compiled files such that, if you can one of the defines, all compiled files need to be recompiled.
With this change, a developer can apply `defines` for anything that uses nanopb only, by using a transitions, or a command line option to set the library to use for nanopb.
> Add Ability To Inject Compilation Options in Bazel Build

- generator/nanopb_generator.py
- tests/message_sizes/dummy.c
- tests/message_sizes/messages2.proto
- tests/options/options_h.expected
Fields that have a user defined different type (such as a FT_POINTER) may still have a known encoded size.
This pull requests computes the encoded sizes of those messages to ensure that, if nanopb has enough information to know the encoded size, it is reported.
> Compute size of all statically known messages

- CMakeLists.txt
When trying to build nanopb as a static library using cmake, it was failing if python is not found even if nanopb_BUILD_GENERATOR is set to OFF.
Example use case is when one already has generated files and wants to build nanopb as a static library using cmake.
Example steps to reproduce:
```
podman run --rm -it -v $(pwd):/mnt/host alpine:latest
apk add cmake make gcc musl-dev
cmake -S /mnt/host -B /tmp/build -Dnanopb_BUILD_GENERATOR=OFF
cmake --build /tmp/build
```
> Make it possible to build the library without python

- generator/nanopb_generator.py
When i was using the C++ lookup generation, I saw that the naming style is hardcoded to be only the "default" style. 
While when a user applies the c-naming style and the C++ lookup by using the command line arguments: `--cpp-descriptors -C`, the naming is not correct in the generated C++ code, giving a compiler error. 
I'm not sure if I overlooked something, this is my first PR.
> Use styled naming when generating c++ lookup code
