nanopb/nanopb

- generator/nanopb_generator.py
* Remove trailing whitespace
* No functional changes
> generator: Remove trailing whitespace

- generator/nanopb_generator.py
As part of a build process, it's often nice to be able to specify where the output files go without having to move them after the fact.
Eventually it might be nice to have an option to output either the `.h` or `.c` file to stdout as well, so it can be piped anywhere.
> Add -D option to specify output directory

- generator/nanopb_generator.py
- generator/proto/nanopb.proto
- pb.h
- pb_decode.c
- pb_encode.c
Based on Pull request #215 and the comments of @PetteriAimonen. Thanks to @fazjaxton
> Proto3 singular fields support

- pb_encode.c
Bug has slipped in at refactoring. Sorry for that ;)
> Fix typo in encoding

- generator/nanopb_generator.py
- generator/proto/nanopb.proto
We need an enum to string method for being able to trivially print enum encoded error codes.
> nanopb: update generator to emit optional enum->string mapping function

- CMakeLists.txt
> WIP: cmake cleanup to support installable host tooling

- pb_encode.c
- tests/field_size_16_proto3/SConscript
- tests/field_size_16_proto3/alltypes.options
- tests/field_size_16_proto3/alltypes.proto
- tests/field_size_16_proto3/decode_alltypes.c
- tests/field_size_16_proto3/encode_alltypes.c
- Occurs with proto3, PB_FIELD_16BIT and submessage > 255 bytes
- Add test case for PB_FIELD_16BIT and proto3
> Fix infinite loop in pb_check_proto3_default_value

- library.json
Would be good to see [here](http://platformio.org/lib/show/431/Nanopb) examples. Thanks.
> Export examples

- pb_encode.c
- tests/without_64bit/SConscript
This is a fix for #285, I modified the unit test to take this into account.
> Fix negative number without 64bit

- CMakeLists.txt
See https://github.com/pytorch/pytorch/issues/4141 and https://github.com/gflags/gflags/issues/113 for context
> Require non-buggy version of cmake

- extra/FindNanopb.cmake
This commit uses protoc using the nanopb plugin to generate source files
in a single step instead of two. A new variable 'NANOPB_OPTIONS' can be
used to pass nanopb options to protoc.
The directory of a generated proto file is always passed as a search
path for option files.
This fixes the calculation of max encoded size for proto files with
imports.
> Use protoc plugin mode for source generation in CMake

- generator/nanopb_generator.py
Use a maximum calculation if submessage sizes are unknown.
> Always return size for messages with OneOf fields

- extra/FindNanopb.cmake
Restore dependency of generated nanopb source and header files on an
options file, if it exists in the same directory and has the name
filename without extension.
Add nanopb CMake variable NANOPB_DEPENDS which is a list of files to be
manually set as dependencies for the generated source and header files.
If these dependencies are options files, the corresponding directory is
passed as an options path.
> Fix CMake options file dependency

- docs/concepts.rst
Add a few lines to the docs to resolve #357.
> Clarify the usage of callback fields inside oneof sections in the docs

- CMakeLists.txt
Follow-up to https://github.com/nanopb/nanopb/commit/a10c771f1e1ae21f3afcce88ce128c80c0b28ec6 to fix cmake
> Remove plugin.proto from CMakeLists.txt

- build.py
- conan-wrapper/CMakeLists.txt
- conanfile.py
- tools/set_version.sh
> Implement conan recipe

- generator/nanopb_generator.py
- pb.h
- tests/cxx_descriptor/SConscript
- tests/cxx_descriptor/message.proto
- tests/cxx_descriptor/message_descriptor.cc
- tests/regression/issue_203/SConscript
- tests/site_scons/site_tools/nanopb.py
Zero-overhead. Allows creating simpler general nanopb C++ wrappers by
examining variable type and not needing macro magic.
> Add C++ message descriptors helper

- generator/proto/Makefile
> fix for issue '390';

- generator/nanopb_generator.py
- generator/proto/nanopb.proto
- tests/typename_mangling/SConscript
- tests/typename_mangling/test_package_initials.c
Here is the fix I propose for a new Typename Mangling mode, see https://github.com/nanopb/nanopb/issues/394
> Adding TypenameMangling.M_PACKAGE_INITIALS

- generator/nanopb_generator.py
- tests/cyclic_messages/cyclic_callback.options
> change generator to raise error on unmatched options and add cli option to disable

- docs/reference.rst
- pb.h
- pb_decode.c
- tests/validate_utf8/SConscript
Check whether incoming strings are valid UTF-8 sequences. Slows down the string processing slightly and slightly increases code size.
> Introduce new compile time flag: PB_VALIDATE_UTF8

- CHANGELOG.txt
Signed-off-by: David Lin <dtwlin@google.com>
> Correct a typo in date on the changelog file

- extra/FindNanopb.cmake
> Revert "Fix nanopb_out path in cmake command"

- .github/workflows/spm.yml
- Package.swift
- SwiftPackage/module.modulemap
- SwiftPackage/nanopb.h
- spm-test/objc/c-header.c
- spm-test/objc/objc-header.m
- spm-test/objc/objc-module.m
- spm-test/swift/main.swift
This is the Swift Package Manager configuration for nanopb we're using for initial Firebase testing with Swift Package Manager.
We may need to use nanopb from a fork because of our [versioning requirements](https://github.com/google/nanopb-podspec), but I'm happy to contribute to making this mergeable if there's interest.
> Swift package manager

- generator/nanopb_generator.py
- use in instead of multiple equals comparison
- remove unnecessary elif skipped by return
> Minor style improvements to nanopb_generator.py

- extra/FindNanopb.cmake
> Get a correct option file name if proto filename is absolute

- generator/nanopb_generator.py
> Don't generate lines with trailing spaces

- generator/protoc-gen-nanopb.bat
- generator/protoc.bat
> Use standard python invocation instead of py.exe launcher

- generator/proto/Makefile
I'm not sure how the Makefile is used in other contexts, but for our use case need to clean the generated python file explicitly some times.
> Add clean target

- docs/migration.md
- pb.h
- tools/set_version.sh
> feat: Change NANOPB_VERSION macro to string

- generator/nanopb_generator.py
When generating code for proto files which used includes, unless all of the includes where passed as inputs I would get an error for types defined in imported files:
```
Could not find enum type %s while generating default values for %s.
Try passing all source files to generator at once, or use -I option.
```
It looks like this was possibly unintentionally introduced with 0bd67e3dea73e03d2b85c373a73ef1879774a5fe. This PR re-enables parsing imports before generating code, with the difference being that it only generates code for the filenames passed as inputs, not also for the files they imported.
> Parse all include files before generating code

- .github/workflows/platformio.yaml
- generator/platformio_generator.py
Fix https://github.com/nanopb/nanopb/issues/731
> PlatformIO: install protobuf compiler dependencies

- generator/nanopb_generator.py
- generator/proto/nanopb.proto
- tests/fallback_type/SConscript
- tests/fallback_type/fallback_type.expected
- tests/fallback_type/fallback_type.options
- tests/fallback_type/fallback_type.proto
As discussed here:
https://github.com/nanopb/nanopb/issues/772#issuecomment-1094100183
Note: testsuite ran and completed successfully.
> make the default fallback strategy for FT_DEFAULT configurable

- generator/platformio_generator.py
Related issue https://github.com/platformio/platformio-core/issues/4467
> Escape Python path (solve issue with a space)

- generator/platformio_generator.py
Related:
* https://github.com/platformio/platformio-core/issues/4467
* https://github.com/nanopb/nanopb/pull/834
> PlatfromIO: Fix to work with spaces in pyhton path.

- generator/nanopb_generator.py
- generator/proto/nanopb.proto
- tests/enum_validate/SConscript
- tests/enum_validate/enum.proto
- tests/enum_validate/enum_validate.c
- tests/namingstyle/naming_style.options
- tests/namingstyle/test_naming_style_c.c
As I wrote in #988 , adding an enum validation function is a feature I'd find useful.
The one big question I have is the type of argument the function should take. Should it be the type of enum used, or should it be some integer type?
Marking as draft until I add tests.
> Enums: add a validation function

- .github/workflows/platformio_tests.yml
Otherwise gets "This environment is externally managed"
> Github workflows: Fix platformio to use venv

- generator/nanopb_generator.py
- tests/namingstyle/test_naming_style_c.c
- tests/oneof/decode_oneof.c
> Add name to unions

- tools/set_version.sh
Tested by running the script locally.
Addresses https://github.com/nanopb/nanopb/issues/1041.
> Set version in MODULE.bazel
